---
name: Linter
description: Lint java code

inputs: { }

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build java app
      uses: ./.github/actions/setup-java

    - name: Run linter
      run: mvn checkstyle:check
      shell: bash
