---
name: Lint Code Base

on: [ push ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build java app
        uses: ./.github/actions/build

      - name: Run linter
        run: mvn checkstyle:check
